# .goreleaser.yml
version: 2

project_name: api-performance-tester

builds:
- id: api-performance-tester
  main: ./perf
  binary: perf
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  - arm

release:
  name_template: "Release {{ .Tag }}"
  github:
    owner: raywall
    name: api-performance-tester

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - 'Merge pull request'
    - 'Merge branch'
